(WIP) Feature/fetch products from Vendure
vuestorefront-community/vendure pull request #221
Opened 2022-06-06 01:15 UTC by qwexvf

## Description

The purpose of this feature is to have a possibility to fetch multiple products with custom fields by using products query from Vendure.

## Related Issue

## Motivation and Context

With some composables you can't fetch the customfields with customqueries and most of them are a little complicated so with this composable is much easier to fetch products the way i want.

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-06-06 01:17 UTC, qwexvf commented
@Baroshem Hi, could you give us some hints about the failling test? it seems that the types are wrong altought i did the same as other tests so i'm not quiet sure where is wrong...

2022-06-06 19:18 UTC, Baroshem commented
Hi @qwexvf 

Thanks for this PR! I will review it tomorrow. I suppose these are just some simple changes that needs to be added to make it work 😉

2022-06-07 11:29 UTC, Baroshem requested changes
Overall it looks really well! I have just added some comments about the things that are not necessary. You can also add some documentation. If not, no worries, I can do that as well :)

Regarding tests, I can fix them as well so just focus on fixing the issues I mentioned and I can take over the rest :)

2022-06-07 11:29 UTC, Baroshem commented on packages/api-client/src/types/API.ts
> +  getProducts(params: any, customQuery?: CustomQuery): Promise<GetProductsResponse>;
You can add here the params generated by the Vendure Grapqhl file. Check out other types as well :)

2022-06-07 11:29 UTC, Baroshem commented on packages/composables/package.json
> +    "@vue-storefront/vendure-api": "link:../api-client"
You do not need this link. But if you do, please remember not to push it to the code repo ;)

2022-06-07 11:29 UTC, Baroshem commented on packages/composables/package.json
> +    "@vue-storefront/vendure-api": "link:../api-client"
You do not need this link. But if you do, please remember not to push it to the code repo ;)

2022-06-07 11:29 UTC, Baroshem commented on packages/theme/.env.example
> -GRAPHQL_API=http://localhost:3000/shop-api
Do not delete this file. It is quite usable :)

2022-06-07 11:29 UTC, Baroshem commented on packages/theme/.env.example
> -GRAPHQL_API=http://localhost:3000/shop-api
Do not delete this file. It is quite usable :)

2022-06-07 11:29 UTC, Baroshem commented on packages/theme/nuxt.config.js
> -  server: {
This is needed as well as vendure is working by default on port 3000. Please, revert this change

2022-06-07 11:29 UTC, Baroshem commented on packages/theme/nuxt.config.js
> -  server: {
This is needed as well as vendure is working by default on port 3000. Please, revert this change

2022-06-07 11:29 UTC, Baroshem commented on packages/theme/package.json
> +    "@vue-storefront/vendure": "file:../composables",
Do not push this to the repo

2022-06-07 11:29 UTC, Baroshem commented on packages/theme/package.json
> +    "@vue-storefront/vendure": "file:../composables",
Do not push this to the repo

2022-06-07 11:29 UTC, Baroshem commented on packages/theme/pages/Home.vue
> +    console.log(req);
If you have tested it and it works, please remove this code. UseProducts is not used by default in the app so we will add the docs explaining how to use it instead :)

2022-06-07 11:29 UTC, Baroshem commented on packages/theme/pages/Home.vue
> +    console.log(req);
If you have tested it and it works, please remove this code. UseProducts is not used by default in the app so we will add the docs explaining how to use it instead :)

2022-06-12 05:30 UTC, qwexvf commented on packages/api-client/src/types/API.ts
> +  getProducts(params: any, customQuery?: CustomQuery): Promise<GetProductsResponse>;
Thanks! I updated the types to use the correct type!!

2022-06-12 05:31 UTC, qwexvf commented
@Baroshem Sorry for the delay! i pushed the changes required from review i hope to get back from you soon!

2022-06-13 06:56 UTC, Baroshem commented
Hey @qwexvf 

Sure, now it looks better. Some final adjustements I will add and we will be able to merge it to our next 1.3.0 version :)

2022-06-13 09:47 UTC, qwexvf commented
@Baroshem Thanks! please let me know if i can help in some way when adding the missing functionalities!

2022-06-15 11:31 UTC, Baroshem commented
@qwexvf 

If you have time, you could also document the feature in the docs section. You can take a look at the useProduct documentation and write something similar for useProducts :)

Also, you can add a new record in 1.3.0 changelog.

2022-06-15 11:32 UTC, Baroshem approved these changes
Small recommendations

2022-06-15 11:32 UTC, Baroshem commented on packages/api-client/src/types/API.ts
> +  getProducts(params: any, customQuery?: CustomQuery): Promise<GetProductsResponse>;
You can add here the params generated by the Vendure Grapqhl file. Check out other types as well :)

2022-06-15 11:32 UTC, Baroshem commented on packages/theme/.env.example
> -TOKEN_METHOD=bearer
This can be left not removed as it is used in the app :)

2022-08-05 08:05 UTC, Baroshem commented
This feature seems to not be that requested so I decided to close this PR as it requires much more work than expected.

I recently found out a way to extend API methods (even create new ones) that can be checked here:

```ts
const gql = require('graphql-tag');

module.exports = {
  integrations: {
    vendure: {
      location: '@vue-storefront/vendure-api/server',
      configuration: {
        api: {
          uri: process.env.GRAPHQL_API,
          // to be used later with authentication
          tokenMethod: process.env.TOKEN_METHOD
        }
      },
      extensions: (extensions) => [
        ...extensions,
        {
          name: 'test',
          extendApiMethods: {
            testApiMethod: async ({ client, config }) => {
              const result = await client.query({ query: gql`
              query products {
                products {
                  items {
                    id
                    customFields
                  }
                }
              }
              `, fetchPolicy: 'no-cache' })
              console.log(result)
            }
          }
        }
      ]
    }
  }
};
```

Then, you can use the above api method like this somewhere in the template:

```ts
const { $vendure } = useVSFContext();
    onSSR(async () => {
      await $vendure.api.testApiMethod()
    });
```

Considering that, there is no need to implement this functionality.

Thanks @qwexvf for the work done and sorry that I have not found the solution earlier :(

2022-08-05 08:05 UTC, closed without merging

2022-08-08 15:04 UTC, qwexvf commented
Thanks for the update!

using `extendApiMethods` is much easier! btw where did u find it?
I knew that i could extend queries but not the api methods....
Is it on the vue-storefront docs?

2022-08-08 15:27 UTC, Baroshem commented
Hey,

I did a lot of manual testing and trying things out. There is an example in the docs but it is aimed and extending current methods, not create new ones. I requested to add it to the official docs but not sure when it will be merged.